const data = [
    {
        questionGroup: [
            "Автономная система управления ракетой – все устройства, формирующие основной управляющий сигнал, находятся на борту летательного аппарата и в процессе полета не получают никакой информации от цели или с командного пункта",
            "Аэродинамическая сила R действует на ракету лишь при полете в плотных слоях атмосферы. Она зависит от размеров и формы ракеты, скорости ивысоты её полёта, а также от величины углов атаки",
            "Гиперзвуковым оружиемявляется ракета, в которых боевая часть двигается на гиперзвуковых скоростях в атмосфере. То есть в промежутке 5000 – 25000 километров в час",
            "Х-47м2 'Кинжал' – это российский гиперзвуковой авиационный ракетный комплекс, который относится к новейшим. Это ракета с ядерным или обычным боезарядом",
            "Гиперзвуковые ракеты (около 10 М) комплекса способны поражать как стационарные объекты, так и надводные корабли: авианосцы, крейсеры, эсминцы и фрегаты",
            "Новая ракета «Кинжал» является не крылатой, а «аэробаллистической», — траектория ракеты поддерживается за счёт высокой скорости",
            "МиГ-31К способен нести 1 ракету и поражать цели на расстоянии до 2000 километров. Также носителями ракет 'Кинжал' могут быть стратегические бомбардировщики Ту-22М3, способные нести 4 ракеты",
            "Ракета'Кинжал', после сброса в заданной точке, далее летела с гиперзвуковой скоростью, превышая скорость звука в 10 раз и маневрируя на всей траектории полёта",
            "Сразу после старта 'Кинжал' залетает в стратосферу и летит на большой скорости вниз. 'Времени для того, чтобы эффективно ее выявить и пробовать сбить, очень мало', – сообщал Игнат",
            "Ракета достигает скорости до 12000 километров в час, перехватить ее на маршевом участке невозможно даже специализированными противоракетными комплексами",
        ],
        translateGroup: [
            "Hệ thống điều khiển tên lửa ô - tô - nôm - tất cả các thiết bị tạo tín hiệu điều khiển khiển chính nằm trên khoang của thiết bị bay và trong quá trình bay không thu nhận bất kỳ thông tin gì từ mục tiêu hoặc từ đài phát lệnh",
            "Lực khí động R chỉ tác động lên tên lửa khi nó bay trong môi trường không khí đặc. Lực này phụ thuộc vào kích thước, dạng tên lửa, vận tốc và độ cao bay cũng như góc tấn công",
            "Vũ khí siêu vượt âm tên lửa có phần chiến đấu chuyển động với tốc độ siêu âm trong khí quyển. Tức nằm trong khoảng 5000-25000 km/h",
            "Х-47м2 'Кинжал' – là tổ hợp tên lửa hàng không siêu vượt âm mới của Nga. Tên lửa có trang bị đầu đạn thường hoặc hạt nhân",
            "Tổ hợp tên lửa siêu vượt âm (khoảng 10Max) có khả năng tiêu diệt các đối tượng cố định cũng như các tàu mặt nước: tàu sân bay, tàu tuần tiễu, tuần dương hạm và tàu khu trục",
            "Tên lửa mới “Кинжал” không phải là tên lửa có cánh mà là tên lửa khí đạn đạo–quỹ đạo của tên lửa được đảm bảo bằng tốc độ cao",
            "Mig-31K có khả năng mang 1 tên lửa và tiêu diệt các mục tiêu với khoảng cách lên đến 2000km. Tương tự phương tiện mang tên lửa Kinzhal khác có thể là máy bay ném bom chiến lược Tu-22M3, vớ ikhả năng mang 4 tên lửa",
            "Tên lửa Кинжал, sau khi thả tại điểm đã xác định trước, tiếp tục bay với vận tốc siêu vượt âm gấp 10 lần vận tốc âm thanh và cơ động trên toàn bộ quỹ đạo bay",
            "Ngay sau khi phóng, tên lửa Kinzhal bay lên tầng bình lưu và bay xuống với tốc độ lớn. “Thời gian để phát hiện ra và bắn hạ nó rất ít” –Ignat cho biết",
            "Tên lửa đạt tốc độ đến 12000 km/h, không thể đánh chặn nó trong giai đoạn hành trình thậm chí bằng các tổ hợp đánh chặn tên lửa chuyên dụng",
        ],
    },

    {
        questionGroup: [
            "Скорость ракеты после начального участка траектории: 2100 м/c. Максимальные перегрузки в процессе полёта — 20-30G (ракета маневрирует в полёте как по высоте, так и по направлению полёта). Максимальная высота траектории — более 1000 км",
            "Межконтинентальные баллистические крылатые ракеты могут подразделяться в зависимости от их размера, скорости (дозвуковая или сверхзвуковая), дальности полёта и места запуска: с земли, воздуха, поверхности корабля или подводной лодки",
            "Определение текущих координат цели и ракеты (например, дальности, азимута и угла места) осуществляется радиолокационной станцией сопровождения. В некоторых комплексах эта задача решается двумя радиолокаторами, один из которых сопровождает цель, а другой – ракету",
            "Самонаведение - управление полетом ракеты осуществляется командами, вырабатываемыми на борту ракеты. Пассивная система - цель ничем не облучается, а головка самонаведения (ГСН) использует энергию, излучаемую целью – инфракрасную или фотоконтрастную",
            "Для визирования ракеты, как правило, применяются радиолокационные линии с активным ответом, т.е. на протяжении всего времени полета к цели ракета на каждый запросный импульс с земли отвечает своим ответным",
            "Автономным называется такое наведение ракеты, которое осуществляется лишь с помощью ее бортовых устройств, без какой-либо связи с наземной аппаратурой и целью. Вся система управления полетом находится на ракете",
            "При ударе, на терминальном участке, скоростьракеты составляет до 3,4 Маха, а угол падения составляет 80–90 градусов, что также требует специализированных противоракетных комплексов для ее эффективного перехватывания",
            "Координатор цели устанавливается на борту ракеты. Он осуществляет слежение за целью и определение ее текущих координат в подвижной системе координат, связанной с ракетой",
            "Система наведения ракетного комплекса образует контур управления управляемой ракетой (УР). Элементы контура управления могут располагаться на земле и на ракете или только на борту ракеты",
            "Координатор цели устанавливается на борту ракеты. Бортовой координатор в общем случае включает антенну приёма сигналов цели, приёмник, устройство определения координат цели, шифратор, передатчик сигналов , содержащих информацию о координатах цели, и передающую антенну",
        ],

        translateGroup: [
            "Vận tốc của tên lửa sau giai đoạn đầu của quỹ đạo đạt 2100 m/s. Quá tải cực đại trong khi bay 20-30G (tên lửa cơ động trong khi bay theo độ cao cũng như theo hướng bay). Trần bay của quỹ đạo – trên 1000 km",
            "Các tên lửa có cánh đạn đạo liên lục địa có thể được phân chia tùy thuộc vào kích thước, vận tốc ( dưới âm hoặc vượt âm), cự ly bay và vị trí phóng của nó: từ mặt đất, trên không, bề mặt tàu hoặc tàu ngầm",
            "Việc xác định các tọa độ tức thời của mục tiêu và tên lửa (ví dụ, cự ly, phương vị, góc tà) được thực hiện bởi đài bám sát ra đa. Ở một vài tổ hợp tổ hợp bài tóan đó được giải quyết bởi  hai đài ra đa, một đài bám sát mục tiêu , còn đài khác- bám sát tên lửa",
            "Tự dẫn – Việc điều khiển bay của tên lửa được thực hiện bởi các lệnh tạo ra trên khoang tên lửa. Hệ thống tự dẫn thụ động – mục tiêu không phát xạ, còn đầu tự dẫn sử dụng năng lượng bức xạ từ mục tiêu – hồng ngoại hoặc tương phản quang ảnh",
            "Để quan sát tên lửa thường sử dụng đường truyền vô tuyến với tín hiệu trả lời tích cực, tức là trong toàn bộ khoảng thời gian bay đến mục tiêu, tên lửa trả lời từng xung hỏi từ mặt đất bằng tín hiệu trả lời của mình",
            "Dẫn ô tô nôm là việc dẫn tên lửa được thực hiện chỉ nhờ các thiết bị trên khoang tên lửa không sử dụng các kênh liên lạc với mặt đất, mục tiêu. Tất cả hệ thống điều khiển nằm trên tên lửa",
            "Khi tấn công, tại giai đoạn cuối, tốc độ tên lửa đạt 3.4 M, còn góc rơi khoảng 80-90 độ, điều này đòi hỏi phải có các tổ hợp đánh chặn tên lửa chuyên dụng để đánh chặn nó một cách hiệu quả",
            "Thiết bị tọa độ mục tiêu được đặt trên khoang tên lửa. Nó thực hiện bám theo mục tiêu và xác định các tọa độ tức thời của nó trong hệ tọa độ di động gắn với tên lửa",
            "Hệ thống dẫn của tổ hợp tên lửa cấu thành vòng điều khiển tên lửa có điều khiển. Các phần tử của vòng điều khiển có thể được bố trí trên mặt đất và trên tên lửa hoặc chỉ trên khoang tên lửa",
            "Thiết bị tọa độ mục tiêu được đặt trên khoang tên lửa. Thiết bị tọa độ trên khoang trong  trường hợp tổng quát bao gồm an ten thu tín hiệu mục tiêu, máy thu, thiết bị xác định tọa độ mục tiêu, thiết bị mã hóa, máy phát tín hiệu, chứa thông tin về các tọa độ mục tiêu an ten phát",
        ],
    },

    {
        questionGroup: [
            "Система телеуправления (дистанционного управления) применяется главным образом в крылатых ракетах. Она состоит из командной аппаратуры, расположенной на командном пункте управления ракетами, исполнительной аппаратуры, размещенной на борту ракеты, и линии связи между командным пунктоми ракетой в полёте",
            "Автономным называется такое наведение ракеты, которое осуществляется лишь с помощью ее бортовых устройств, без какой-либо связи с наземной аппаратурой и целью. Вся система управления полетом находится на ракете, которая осуществляет полет по программе, рассчитанной на основании координат цели, до старта ракеты",
            "По способу наведения различают самонаводящиеся и телеуправляемые управляемые ракеты. Самонаводящейся называется ракета, на борту которой установлена аппаратура управления ее полетом. Телеуправляемыми называют управляемая ракета (УР), управляемые  наземными средствами управления. По типу боевого заряда различают УР с обычными и ядерными боевыми частями",
            "Сила веса G ракеты направлена вниз к центру Земли и меняется за счет выгорания топлива и изменения ускорения g силы тяжести с высотой. Аэродинамическая сила R действует на ракету лишь при полете в плотных слоях атмосферы. Она зависит от размеров и формы ракеты, скорости и высоты её полёта, а также от величины углов атаки и скольжения",
            "В системах телеуправления передача команд управления с пункта наведения на бортовое устройство управляемой ракеты осуществляется посредством аппаратуры, образующей командную радиолинию управления. Эта линия обеспечивает передачу команд управления полетом ракеты, разовых команд, изменяющих режим работы бортовой аппаратуры",
        ],
        translateGroup: [
            "Hệ thống điều khiển từ xa được sử dụng chủ yếu trong tên lửa hành trình. Nó bao gồm các thiết bị chỉ huy đặt tại sở chỉ huy tên lửa, thiết bị điều hành đặt trên tên lửa và đường dây liên lạc giữa sở chỉ huy và tên lửa đang bay",
            "Hướng dẫn tự động của tên lửa chỉ được thực hiện với sự trợ giúp của các thiết bị trên tàu, không có bất kỳ liên lạc nào với thiết bị mặt đất và mục tiêu. Toàn bộ hệ thống điều khiển bay được đặt trên tên lửa, thực hiện chuyến bay theo chương trình được tính toán trên cơ sở tọa độ mục tiêu trước khi phóng tên lửa",
            "Theo phương pháp dẫn đường, phân biệt tên lửa dẫn đường tự dẫn và điều khiển từ xa. Tên lửa dẫn đường là một tên lửa trên máy bay được trang bị thiết bị điều khiển bay. Tên lửa điều khiển từ xa là tên lửa dẫn đường (UR) được điều khiển bởi các cơ sở điều khiển trên mặt đất. Theo loại đầu đạn, UR với đầu đạn thông thường và hạt nhân được phân biệt",
            "Lực trọng lượng g của tên lửa được hướng xuống tâm Trái đất và thay đổi do sự đốt cháy nhiên liệu và sự thay đổi gia tốc g trọng lực theo độ cao. Lực khí động học R chỉ tác động lên tên lửa khi bay trong các lớp dày đặc của khí quyển. Nó phụ thuộc vào kích thước và hình dạng của tên lửa, tốc độ và độ cao bay của nó, cũng như kích thước của các góc tấn công và trượt",
            "Trong các hệ thống điều khiển từ xa, việc truyền lệnh điều khiển từ trạm dẫn đường đến thiết bị trên tàu của tên lửa dẫn đường được thực hiện bằng các thiết bị tạo thành đường điều khiển vô tuyến chỉ huy. Dòng này đảm bảo truyền lệnh điều khiển bay tên lửa, lệnh một lần thay đổi chế độ hoạt động của thiết bị trên máy bay",
        ],
    },

    {
        questionGroup: [
            "Дальняя граница зоны поражения определяется на малых высотах дальностями обнаружения и устойчивого автоматического сопровождения цели, а на остальных высотах – соотношением располагаемых и потребных перегрузок, обеспечивающих требуемую точность наведения ракеты на цель",
            "Командная система телеуправления первого рода реализуется достаточно простым составом бортовой аппаратуры ракеты. Основным недостатком способа является зависимость величины ошибки наведения ракеты от дальности стрельбы по целям",
            "Радиолокационные системы самонаведения получили широкое распространение в ракетных комплексах из-за их независимости действия от метеорологических условий и возможности наведения ракеты на цель любого типа и на различные дальности",
            "Баллистическая ракета – это ракета, имеющая баллистическую траекторию на большей части пути её полета. Баллистические ракеты подразделяются по дальности полёта. Баллистические ракеты могут запускаться с морских и наземных носителей",
            "Ракеты обычно классифицируются по типу траектории полёта, по месту и направленности запуска, по дальности полёта, по типу двигателя, по типу боеголовки, по типу систем управления и наведения. В зависимости от типа траектории полёта различаюткрылатые ракеты и межконтинентальные баллистические крылатые ракеты",
            "Зона поражения характеризуется границами: верхней, нижней, дальней и ближней. Верхняя граница зоны поражения определяется возможностями ракеты, методом наведения и скоростью цели",
            "Управление ракетой осуществляется посредством выработки и передачи на ракету команд управления. Команды управления кодируются и передаются от станции наведения ракетна ракету в виде радиосигналов",
            "Бортовая аппаратура управления полетом обеспечивает управление полетом ракеты. В телеуправляемых ракетах она представляет собой часть аппаратуры управления, предназначенную для приёма команд с наземных средств наведения и передачи их на автопилот",
            "Нижняя граница зоны поражения определяется влиянием земли на работу радиолокационных средств огневого комплекса (каналы визировании цели и ракеты, канал радиоуправления ракетой, радиовзрыватель), а также колебательным характером вывода ракеты на кинематическую траекторию",
            "Автопилот представляет собой устройство (часть системы уравления), содержащее измерители положения и параметров движения ракеты, блоки формирования сигналов управления, фильтрации, преобразования и усиления измеренных сигналов, приводы рулей",
            "Неуправляемые ракеты обладают рядом положительных свойств, благодаря чему они получили широкое развитие и применение. К таким свойствам относится их универсальность, большой диапазон дальностей стрельбы, высокая боеготовность, маневренность и скорострельность",
            "При трёхточечном методе наведения кинематическое уравнение метода задается в виде уравнения связи координат цели и ракеты, измеряемых относительно начала координат, находящегося в третьей точке",
            "В зависимости от тактического использования, характера поражаемых целей и дальности стрельбы управление ракетами в полёте может осуществляться с помощью различных систем. По принципу действия эти системы подразделяются на три основные группы: автономное управление ,телеуправление и самонаведение",
            "Головка самонаведения ракеты автономно осуществляет сопровождение цели, определяет параметр рассогласования и формирует команды управления ракетой.По виду энергии, которую излучает или отражает цель, системы самонаведения разделяются на радиолокационные и оптические",
            "Траектория полёта неуправляемой ракеты имеет два участ¬ка: активный и пассивный. На активном участке производится разгон ракеты до заданной скорости и набор высоты. Затем двигатель выключается и начинается пассивный участок",
            "Для наведения ракеты на цель используются как активный участок полета (с работающим маршевым двигателем), так и пассивный (После окончания работы маршевого двигателя). Активный участок полета в зависимости от высоты полета составляет 7...15 км, а пассивный участок является его продолжением и составляет 4...10 км",
            "В системах телеуправления передача команд управления с пункта наведения на бортовое устройство управляемой ракеты осуществляется посредством аппаратуры, образующей командную радиолинию управления",
            "Управление ракетой в полете, ее стабилизация на заданной траектории и вывод в район нахождения цели обеспечивает инерционная система управления. Наведение ракеты на цель на конечном участке осуществляется по сигналам от радиолокационной системы наведения",
            "Устройство ракет определяется их наз¬начением, средствами запуска, способами управления в полёте, принципами наведения на цель, дальностью стрельбы. Управляемые ракеты состоят из головной части с боевым зарядом и взрывателем, двигателя, стаби¬лизирующих устройств, приборов управления",
            "Сверхзвуковая крылатая ракета движется со скоростью около М=2 …3, то есть преодолевает за секунду расстояние приблизительно в 1 километр. Модульная конструкция ракеты и её способность запускаться под различным углом наклона, позволяют запускать ее  с различных носителей",
        ],
        translateGroup: [
            "Giới hạn xa của vùng tiêu diệt ở các độ cao thấp được xác  định bởi cự ly phát hiện và sự bám sát tự động ổn định mục tiêu, còn ở các độ cao khác xác định bởi tỷ số giữa quá tải phát huy và quả tải yêu cầu, đảm bảo độ chính xác yêu cầu dẫn tên lửa tới mục tiêu",
            "Hệ thống dẫn từ xa bằng lệnh loại một được thực hiện bởi các thành phần khá đơn giản của thiết bị trên khoang tên lửa. Sự phụ thuộc của độ lớn sai số dẫn tên lửa vào cự ly bắn các mục tiêu là nhược điểm cơ bản của phương pháp",
            "Hệ thống tự dẫn vô tuyến có  sử dụng rộng rãi trong các tổ hợp tên lửa bởi vì sự độc lập của  hoạt động của chúng đối với điều kiện khí tượng và khả năng dẫn tên lửa tới mục tiêu mọi dạng và tới các cự ly khác nhau",
            "Tên lửa đạn đạo- là tên lửa có quỹ đạo đạn đạo trên phần lớn quãng đường bay của chúng. Các tên lửa đạn đạo được phân chia theo cự ly. Các tên lửa đạn đạo có thể được phóng từ các vật mang trên mặt biển và mặt nước",
            "Tên lửa thường được phân loại theo loại đường bay, theo vị trí và hướng phóng, theo tầm bay, theo loại động cơ, theo loại đầu đạn cũng như theo loại hệ thống điều khiển và dẫn đường. Tùy thuộc vào loại quỹ đạo bay, tên lửa hành trình và tên lửa hành trình đạn đạo xuyên lục địa được phân biệt",
            "Giới hạn vùng tiêu diệt được đặc trưng bởi các giới hạn: trên, dưới, xa, gần. Giới hạn xa của vùng tiêu diệt được xác định bởi khả năng của tên lửa, phương pháp dẫn và tốc độ mục tiêu",
            "Việc điều khiển tên lửa được thực hiện nhờ việc tạo và truyền lên tên lửa các lệnh điều khiển. Lệnh điều khiển được mã hóa và truyền từ đài dẫn tên lửa đến tên lửa dưới dạng tín hiệu vô tuyến",
            "Thiết bị điều khiển chuyến bay trên tàu cung cấp khả năng kiểm soát chuyến bay của tên lửa. Trong tên lửa điều khiển từ xa, nó là một phần của thiết bị điều khiển được thiết kế để nhận lệnh từ thiết bị dẫn đường trên mặt đất và truyền chúng đến hệ thống lái tự động",
            "Giới hạn dưới của vùng tiêu điệt được xác định bởi sự ảnh hưởng của trái đất tới hoạt động của các thiết bị vô tuyến của tổ hợp hỏa lực ( các kênh quan sát mục tiêu và tênl ửa, kênh điều khiển vô tuyến tên lửa, ngòi nổ vô tuyến), cũng như đặc trưng dao động của việc đưa tên ửa vào quỹ đạo động",
            "Thiết bị tự lái là thiết bị ( một phần của hệ thống điều khiển) bao gồm thiết bị xác định vị trí và các tham số chuyển động của tên lửa, khối tạo tín hiệu điều khiển, bộ lọc, bộ biến đổi và khuếch đại tín hiệu đo được, thiết bị truyền động cánh lái",
            "Các tên lửa không điều khiển có một loạt tính chất tích cực, cho phép chúng được phát triển và áp dụng rộng rãi. Các tính chất đó bao gồm tính đa năng, dải cự ly bắn lớn, khả năng sẵn sàng chiến đấu cao, tính cơ động và tốc độ bắn",
            "Khi dẫn theo phương pháp ba điểm, phương trình động học của phương pháp dẫn được cho dưới dạng phương trình liên hệ tọa độ mục tiêu và tên lửa, được đo tương đối so với gốc tọa độ, nằm ở điểm thức ba",
            "Tùy thuộc vào mục đích sử dụng chiến thuật, tính chất của mục tiêu bị tấn công và tầm bắn, tên lửa đang bay có thể được điều khiển bằng nhiều hệ thống khác nhau. Dựa trên nguyên lý hoạt động, các hệ thống này được chia thành 3 nhóm chính: điều khiển tự động, điều khiển từ xa và dẫn đường",
            "Đầu dẫn tên lửa tự động theo dõi mục tiêu, xác định tham số không khớp và tạo ra các lệnh điều khiển tên lửa. Tùy theo loại năng lượng mà mục tiêu phát ra hoặc phản xạ, hệ thống dẫn đường được chia thành radar và quang học",
            "Quỹ đạo tên lửa không điều khiển có hai đoạn: Chủ động và thụ động. Ở trên đoạn chủ động, sự tăng tốc tên lửa đến vận tốc cho trước và lấy độ cao được thực hiện. Sau đó động cơ ngắt và bắt đầu đoạn thụ động",
            "Để hướng tên lửa vào mục tiêu, người ta sử dụng cả giai đoạn bay chủ động (với động cơ chính đang chạy) và giai đoạn bị động (sau khi động cơ chính hoạt động xong). Đoạn bay chủ động, tùy thuộc vào độ cao chuyến bay, là 7...15 km, và đoạn bị động là phần tiếp theo của nó và là 4...10 km",
            "Trong các hệ thống điều khiển từ xa việc phát lệnh điều khiển từ đài dẫn tới thiết bị trên khoang của tên lửa có điều khiển được thực hiện bởi thiết bị  tạo đường truyền  lệnh điều khiểnvô tuyến",
            "Việc điều khiển, ổn định tên lửa ở quỹ đạo cho trước và đưa vào vùng quan sát mục tiêu được đảm bảo nhờ hệ thống điều khiển quán tính. Việc dẫn tên lửa tới mục tiêu ở trên đoạn cuối của quỹ đạo được thực hiện theo các tín hiệu từ hệ thống dẫn ra đa",
            "Thiết kế của tên lửa được xác định bởi mục đích, phương tiện phóng, phương pháp điều khiển khi bay, nguyên tắc nhắm mục tiêu và tầm bắn. Tên lửa dẫn đường bao gồm đầu đạn có đầu đạn và ngòi nổ, động cơ, thiết bị ổn định và thiết bị điều khiển",
            "Tên lửa hành trình siêu thanh chuyển động với tốc độ khoảng M = 2 ... 3, tức là nó bay được quãng  đường xấp xỉ 1 km trong một giây. Cấu trúc mô-đun của tên lửa và khả năng phóng ở nhiều góc nghiêng khác nhau cho phép nó được phóng từ nhiều phương tiện mang khác nhau",
        ],
    },
    {
        questionGroup: [
            "Системами телеуправления называются такие, в которых движение ракеты определяется наземным пунктом наведения, непрерывно контролирующим параметры траектории цели и ракеты. В зависимости от места формирования команд  управления рулями ракеты эти системы делятся на системы наведения по лучу и командные системы телеуправления",
            "Измеренные координаты цели и ракеты подаются в вычислительное устройство (ВУ). ВУ формирует команды в соответствии с выбранным методом наведения и принятым параметром управления. Эти команды принимаются бортовым приемником ракеты, усиливаются через автопилот выдаются на рули",
            "Станция наведения ракет – совокупность устройств, предназначенных для непрерывного определения координат целей и ракет, выработки команд управления и передачи их на борт ракеты. Определение координат целей и ракет осуществляется радиолокационными, оптическими, инфракрасными, лазерными и другими устройствами сопровождения",
            "Самоходная пусковая установка (СПУ)(9П78-1) предназначена для хранения, транспортировки, подготовки и запуска по цели двух ракет. Полная масса 42 т, полезная нагрузка 19 т, скорость передвижения по шоссе/грунтовой дороге 70/40 км/ч, запас хода по топливу 1000 км",
            "В режиме управления на автопилот поступают сигналы от бортовой аппаратуры управления. При этом для получения заданной траектории полета ракеты, в автопилот введены специальные гироскопы с тремя степенями свободы, выдающие сигналы, пропорциональные отклонению ракеты от заданных направлений в горизонтальной и вертикальной плоскостях",
            "Автопилот осуществляет управление полетом ракеты в двух независимых плоскостях управления, а также стабилизацию ракеты по крену. До начала радиоуправления автопилот функционирует в автономном режиме и выполняет функцию стабилизации положения продольной оси ракеты для сохранения направления её полёта после старта",
            "Ракетный комплекс «Искандер» является самым опасным оружием ВС РФ, так как имеет большую дальность и возможность преодоления ПРО, может сразу привести к огромному ущербу в случае нанесения ударов «Искандерами» по аэродромам, логистическим центрам и другим подобным объектам",
            "Комплекс «Искандер-М» использует высотную сверхманёвренную квазибаллистическую ракету со стелс-технологиями,сбрасываемым модулем РЭБ и ложными мишенями с целью обхода систем ПРО. Комплекс «Искандер-К» использует крылатую ракету Р-500 со сверхнизкой траекторией полёта на высоте 6-7 м с огибанием рельефа местности",
            "Пуск ракеты необходимо осуществлять таким образом, чтобы наведение её на цель заканчивалось в зоне поражения. Поэтому для правильного выбора момента пуска ракеты требуется предсказание точки встречи ракеты с целью в системе координат, в которой задана зона поражения ракетного комплекса",
        ],
        translateGroup: [
            "Các hệ thống mà trong đó chuyển động của tên lửa được xác định bởi đài dẫn mặt đất và liên tục kiểm tra các tham số quỹ đạo của mục tiêu và tên lửa được gọi là hệ thống điều khiển từ xa. Tùy thuộc vào vị trí tạo các lệnh điều khiển cánh lái, các tên lửa của hệ thống đó được chia thành hệ thống dẫn từ xa theo tia và hệ thống dẫn từ xa theo lệnh",
            "Các tọa độ đo được của mục tiêu và tên lửa được cấp đến thiết bị tính toán. Thiết bị tính toán tạo ra các lệnh  tương ứng với phương pháp dẫn đã chọn và các tham số điều khiển thu được. Các lệnh đó thu bởi thiết bị thu trên khoang tên lửa, khuếch đại và qua thiết bị tự lái truyền tới cánh lái",
            "Đài dẫn tên lửa – tập hợp các thiết bị  dùng để liên tục xác định các tọa độ của mục tiêu và tên lửa, tạo các lệnh điều khiển và truyền chúng lên khoang tên lửa. Việc xác định tọa độ mục tiêu và tên lửa được thực hiện bởi các thiết bị ra đa, quang, hồng ngoại, la ze và các thiết bị bám sát khác",
            "Xe bệ phóng tự hành (9P78-1) dùng để bảo quản, vận chuyển, chuẩn bị và phóng 2 tênlửa đến mục tiêu. Khối lượng tổng thể 42 tấn, tải trọng có ích 19 tấn, tốc độ di chuyển theo đường nhựa/đường đất là 70/40 km/h, nhiên liệu dự phòng đi được 1000km",
            "Trong chế độ điều khiển, các tín hiệu từ thiết bị điều khiển trên khoang truyền tới thiết bị tự lái. Khi đó để thu được quỹ đạo bay cho trước của tên lửa, trong thiết bị tự lái đưa vào các con quay ba bậc tự do chuyên dụng  tạo các tín hiệu tỷ lệ độ lệch của tên lửa so với hướng cho trướng trong các mặt phẳng ngang và đứng",
            "Hệ thống lái tự động điều khiển chuyến bay của tên lửa trong hai mặt phẳng điều khiển độc lập, cũng như ổn định tên lửa khi lăn. Trước khi bắt đầu điều khiển vô tuyến, hệ thống lái tự động hoạt động ở chế độ tự động và thực hiện chức năng ổn định vị trí trục dọc của tên lửa để duy trì hướng bay sau khi phóng",
            "Tổ hợp tên lửa Iskander là vũ khí nguy hiểm nhất của Quân đội Nga, do nó có tầm xa lớn và khả năng vượt qua lớp phòng thủ tên lửa, có thể gây thiệt hại cực lớn khi tấn công bằng Iskander vào các sân bay, trung tâm hậu cần và các đối tượng tương tự khác",
            "Tổ hợp “Iskander-M” sử dụng tên lửa cận đạn đạo có trần bay cao, khả năng cơ động lớn với công nghệ tàng hình Stealth, các mô đun thả gây nhiễu điện tử và mục tiêu giả nhằm mục đích vượt qua lớp phòng thủ tên lửa. Tổ hợp “Iskander-K” sử dụng tên lửa có cánh R-500 có quỹ đạo bay cực thấp 6-7m và bám theo bề mặt địa hình",
            "Việc phóng tên lửa cần thực hiện để việc dẫn nó tới mục tiêu kết thúc ở vùng tiêu diệt. Do đó để chọn đúng thời điểm phóng  yêu cầu dự đoán điểm tên lửa gặp mục tiêu trong hệ tọa độ mà trong đó đưa ra vùng tiêu diệt của tổ hợp tên lửa",
        ],
    },
];

export { data };
